config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'application#home'

  post 'circumference_measurements', to: 'circumference_measurements#calculate'
  post 'skin_fold_measurements', to: 'skin_fold_measurement#calculate'

  namespace :admin do
    resources :users
    resources :appointments, only: [:new, :destroy, :create, :edit, :update, :show]
    resources :anthropometric_evaluations
    resources :users do
      resources :appointments, only: [:index, :show]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  date_time  :datetime
#  notes      :string
#

class Appointment < ApplicationRecord
  belongs_to :user
  has_one :anthropometric_evaluation, dependent: :destroy


  validates_presence_of :date_time

end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < Admin::BaseController

  def index
    @user = User.find(params[:user_id])
    @appointments = @user.appointments.eager_load(:anthropometric_evaluation)
    render :index
  end

  def new
    @appointment = Appointment.new
    @users = User.all.order('first_name')
    render :new
  end

  def create
    @appointment = Appointment.new(user: user, date_time: DateTime.now)
    if @appointment.save
      flash[:success] = 'New Appointment created'
      redirect_to admin_appointment_path(@appointment)
    else
      flash[:error] = 'Appointment could not be created'
      redirect_to :back
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @user = @appointment.user
    if @appointment.destroy
      flash[:success] = 'Appointment has been successfully deleted'
    else
      flash[:alert] = 'Could not delete appointment'
    end
    redirect_to admin_user_appointments_path(@user)
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(notes: params[:appointment][:notes])
      flash[:sucess] = 'Appointment Notes Saved'
    else
      flash[:error] = 'Notes could not be saved'
    end
    render :show
  end

  private

  def appointment_params
    params.require(:appointment).permit(:user_id, :date, :time, :notes)
  end

  def user
    @user ||= User.find appointment_params[:user_id]
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @users = User.all.order('first_name')
    render :new
  end

  def create
    @appointment =  Appointment.new(user_params)
    if @appointment.save
      flash[:success] = 'New Appointment created'
      redirect_to appointment_path(@appointment)
    else
      flash[:error] = 'Appointment could not be created'
      redirect_to :back
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  private

  def user_params
    params.require(:appointment).permit(:user_id)
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/admin/appointments/index.html.haml
%p#notice= notice
%h5
  %strong
    Appointments History for
    = link_to @user.full_name, admin_user_path(@user)
%table{class: 'responsive-table bordered'}
  %thead
    %tr
      %th{colspan: 1} Date/Time
      %th{class: 'col l6'} Notes
      %th{class: 'col l3'}

  %tbody  
    - @appointments.each do |appointment|
      - evaluation = appointment.anthropometric_evaluation
      %tr
        %td{colspan: 1}= appointment.date_time.to_s(:human_schedule)
        -#TODO Add show more/less
        %td{colspan: 5}= appointment.notes
        %td{class: 'col l3'}= link_to 'Go To Evaluation', admin_anthropometric_evaluation_path(evaluation) if evaluation
        %td= button_to 'X', admin_appointment_path(appointment), method: :delete, class: 'btn red darken-2', data: { confirm: 'Are you sure? This will delete any Evaluations made during this appointment'}

app/views/admin/appointments/new.html.haml
.container
  = form_for(@appointment, url: admin_appointments_path) do |f|
    %h5 New Appointnment
    .input-field
      = f.select :user_id, @users.collect { |p| [ p.full_name, p.id ] }, placeholder: 'Select a client', required: true, include_blank: true
      = f.label :client, for: 'appointment[user_id]'
    %div
      = f.submit 'Start Appointment', class: 'btn btn-link'

app/views/admin/appointments/show.html.haml
%h5
  %strong
    Appointment for
    = link_to @appointment.user.full_name, admin_user_path(@appointment.user)
.row
  %strong= @appointment.date_time.strftime('%a, %-d %b %Y at %H:%M')
.row
  = form_for @appointment, url: admin_appointment_path, method: :patch, class: 'col s12' do |f|
    .input-field
      = f.text_area :notes, class: 'materialize-textarea'
      = f.label :notes
    = f.submit 'Save Notes', class: :btn
  %br/
  = form_tag '/admin/anthropometric_evaluations/new', method: :get do
    = hidden_field_tag :user_id, @appointment.user.id
    = hidden_field_tag :appointment_id, @appointment.id
    = submit_tag 'New Evaluation for this Client', class: 'btn btn-link'