config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'application#home'

  post 'circumference_measurements', to: 'circumference_measurements#calculate'
  post 'skin_fold_measurements', to: 'skin_fold_measurement#calculate'

  namespace :admin do
    resources :users
    resources :appointments, only: [:new, :destroy, :create, :edit, :update, :show]
    resources :anthropometric_evaluations
    resources :users do
      resources :appointments, only: [:index, :show]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anthropometric_evaluation.rb
# == Schema Information
#
# Table name: anthropometric_evaluations
#
#  id                  :integer          not null, primary key
#  appointment_id      :integer          not null
#  fat_percentage      :decimal(5, 2)
#  fat_mass            :decimal(5, 2)
#  lean_mass           :decimal(5, 2)
#  abdomen             :decimal(5, 2)
#  waist               :decimal(5, 2)
#  hip                 :decimal(5, 2)
#  arm                 :decimal(5, 2)
#  weight              :decimal(6, 3)
#  height              :decimal(6, 3)
#  bmi                 :decimal(6, 3)
#  triceps             :decimal(5, 2)
#  subscapular         :decimal(5, 2)
#  thigh               :decimal(5, 2)
#  iliac_crest         :decimal(5, 2)
#  abdominal           :decimal(5, 2)
#  chest               :decimal(5, 2)
#  axilla              :decimal(5, 2)
#  body_fat            :decimal(5, 2)
#  body_fat_percentage :decimal(5, 2)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  notes               :string
#  user_id             :integer
#

class AnthropometricEvaluation < ApplicationRecord
  belongs_to :appointment
  belongs_to :user
  has_one :bmi_measurement
  has_one :body_composition
  has_one :circumference_measurement
  has_one :skin_fold_measurement

  validates_presence_of :fat_percentage, :fat_mass, :lean_mass, :weight, :height,
                        :bmi, :triceps, :subscapular, :thigh, :iliac_crest, :abdominal, :chest, :axilla



  delegate :date_time, to: :appointment

  def results
    attributes.slice('fat_percentage', 'fat_mass', 'lean_mass', 'weight')
  end
end

app/controllers/admin/anthropometric_evaluations_controller.rb
class Admin::AnthropometricEvaluationsController < Admin::BaseController

  before_action :load_evaluation, only: [:show, :edit, :update, :destroy]
  before_action :load_appointment, only: [:show, :edit, :update]
  before_action :load_user, only: [:show, :edit, :destroy]


  def index
    @user = User.find(params[:user_id])
    @evaluations = @user.evaluations
  end

  def new
    @appointment = Appointment.find(params[:appointment_id])
    @user = @appointment.user
    @evaluation = AnthropometricEvaluation.new
  end

  def create
    @appointment = Appointment.find(params[:appointment_id])
    @evaluation = AnthropometricEvaluation.new(
        evaluation_params.merge(appointment_id: @appointment.id, user: @appointment.user)
    )
    @user = @evaluation.user
    if @evaluation.save
      flash[:success] = 'Saved Evaluation with success'
      redirect_to admin_user_appointments_path(@user)
    else
      flash[:error] = @evaluation.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    if @evaluation.update(evaluation_params)
      flash[:success] = 'Evaluation has been updated'
      redirect_to admin_anthropometric_evaluation_path(@evaluation)
    else
      flash[:notice] = @evaluation.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    if @evaluation.destroy
      flash[:success] = 'Evaluation deleted with success'
      redirect_to admin_anthropometric_evaluations_path(user_id: @user.id)
    else
      flash[:notice] = 'There was an error and evaluation could not be destroyed'
    end
  end

  private

  def load_appointment
    @appointment = @evaluation.appointment
  end

  def evaluation_params
    params[:anthropometric_evaluation].permit(:fat_percentage, :fat_mass, :lean_mass, :abdomen, :waist, :hip, :arm,
                                              :weight, :height, :bmi, :triceps, :subscapular, :thigh, :iliac_crest,
                                              :abdominal, :chest, :axilla, :notes)
  end

  def load_evaluation
    @evaluation = AnthropometricEvaluation.find(params[:id])
  end

  def load_user
    @user = @evaluation.user
  end
end

app/controllers/anthropometric_evaluations_controller.rb
class AnthropometricEvaluationsController < ApplicationController

  before_action :load_appointment
  before_action :load_client
  before_action :load_evaluation, only: :new

  def create
    # binding.pry
    @evaluation = AnthropometricEvaluation.new(evaluation_params.merge(appointment_id: @appointment.id))
    if @evaluation.save
      flash[:success] = 'Saved Evaluation with success'
    else
      flash[:error] = @evaluation.errors.full_messages.join(', ')
      render :new
      # body_density_adult_male = 1,11200000 - ((0,00043499 * @total_sum) + (0,00000055 * (@total_sum ** 2)) - (0,0002882 * @age)
    end
  end

  private

  def load_appointment
    @appointment = Appointment.find(params[:appointment_id])
  end

  def load_client
    @user = @appointment.user
  end

  def load_evaluation
    @evaluation = AnthropometricEvaluation.new
  end

  def evaluation_params
    params[:anthropometric_evaluation].permit(:fat_percentage, :fat_mass, :lean_mass, :abdomen, :waist, :hip, :arm, :weight, :height,
                                              :bmi, :triceps, :subscapular, :thigh, :iliac_crest, :abdominal, :chest, :axilla)
  end

end

app/views/admin/anthropometric_evaluations/_form.html.haml
.row
  .col.s12.m6.l4
    = hidden_field_tag :appointment_id, @appointment.id
    %h5 Circumferences
    .input-field
      = e.number_field :abdomen
      %label{class: 'active'} Abdomen (cm)
    .input-field
      = e.number_field :waist
      %label{class: 'active'} Waist (cm)
    .input-field
      = e.number_field :hip
      %label{class: 'active'} Hips (cm)
    .input-field
      = e.number_field :arm
      %label{class: 'active'} Arm (cm)
    %h5 BMI
    .input-field
      = e.number_field :height
      %label{class: 'active'} Height (cm)
    .input-field
      = e.number_field :weight
      %label{class: 'active'} Weight
  .col.s12.m6.l4
    %h5 Skin Folds
    .input-field
      = e.number_field :triceps
      %label{class: 'active'} Triceps (mm)
    .input-field
      = e.number_field :subscapular
      %label{class: 'active'} Subscapular (mm)
    .input-field
      = e.number_field :thigh
      %label{class: 'active'} Thigh (mm)
    .input-field
      = e.number_field :abdominal
      %label{class: 'active'} Abdominal (mm)
    .input-field
      = e.number_field :iliac_crest
      %label{class: 'active'} Iliac crest (mm)
    .input-field
      = e.number_field :chest
      %label{class: 'active'} Chest (mm)
    .input-field
      = e.number_field :axilla
      %label{class: 'active'} Axilla (mm)
  .col.s12.m6.l4
    %div
      %h5 Results
      .div
        %label{class: 'active'} BMI
        = e.number_field :bmi,  step: :any
    %div
      %div
        %label{class: 'active'} Lean Mass (kg)
        = e.number_field :lean_mass,  step: :any
    %div
      %div
        %label{class: 'active'} Body Fat (kg)
        = e.number_field :fat_mass,  step: :any
    %div
      %div
        %label{class: 'active'} Body Fat (%)
        = e.number_field :fat_percentage,  step: :any
    %div
      .input-field
        = e.text_area :notes, class: 'materialize-textarea'
        = e.label :notes, class: 'active'

app/views/admin/anthropometric_evaluations/edit.html.haml
%h4
  Evaluation for
  = link_to @user.full_name, admin_user_path(@user)
= form_for @evaluation, url: admin_anthropometric_evaluation_path do |e|
  = render 'form', e: e
  .col.s12.m6.l4
    = e.submit 'Save' , class:'btn btn-primary', style: 'margin-top: 13px'

app/views/admin/anthropometric_evaluations/index.html.haml
%p#notice= notice
%h5
  Evaluations History for
  = link_to @user.full_name, admin_user_path(@user)
%table{class: 'responsive-table bordered'}
  %thead
    %tr
      %th Evaluation Date
      %th{class: 'col l6'} Results
      %th{class: 'col l3'} Notes

  %tbody
    - @evaluations.each do |evaluation|
      - results = evaluation.results
      %tr
        %td{colspan: 1}= link_to evaluation.date_time.to_s(:human_schedule), admin_anthropometric_evaluation_path(evaluation)
        %td
          - results.each do |name, value|
            %div
              #{name.to_s.gsub(/_/, ' ')}:
              = value

        %td{colspan: 5}= evaluation.notes
        %td= button_to 'X', admin_anthropometric_evaluation_path(evaluation), method: :delete, class: 'btn red darken-2', data: { confirm: 'Are you sure? '}

app/views/admin/anthropometric_evaluations/new.html.haml
%h4
  Evaluation for
  = link_to @user.full_name, admin_user_path(@user)
= form_for @evaluation, url: admin_anthropometric_evaluations_path do |e|
  = render 'form', e: e, appointment: @apppointment
  .col.s12.m6.l4
    = e.submit 'Save' , class:'btn btn-primary', style: 'margin-top: 13px'

app/views/admin/anthropometric_evaluations/show.html.haml
%h4
  Evaluation for
  = link_to @user.full_name, admin_user_path(@user)
= form_for @evaluation, url: admin_anthropometric_evaluations_path do |e|
  = render 'form', e: e
  .col.s12.m6.l4= link_to 'Edit', edit_admin_anthropometric_evaluation_path(@evaluation), class: 'btn'