config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root to: 'application#home'

  post 'circumference_measurements', to: 'circumference_measurements#calculate'
  post 'skin_fold_measurements', to: 'skin_fold_measurement#calculate'

  namespace :admin do
    resources :users
    resources :appointments, only: [:new, :destroy, :create, :edit, :update, :show]
    resources :anthropometric_evaluations
    resources :users do
      resources :appointments, only: [:index, :show]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html.main{class: 'condensed light'}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Nutrihelper
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0", :name => "viewport"}/
  %body
    %nav
      .nav-wrapper
        = link_to 'NutriHelper', root_path, class: 'brand-logo'
        %a{href:"#", 'data-activates':"mobile-demo", class:"button-collapse"}
          %i{class:"material-icons"} menu
        = content_for :navbar do
          - if current_user&.admin?
            %li= link_to 'New Appointment', new_admin_appointment_path
            %li= link_to 'New Client', new_admin_user_path
            %li= link_to 'All Clients', admin_users_path
          - if current_user
            %li= "Logged in as #{current_user.first_name}"
            %li= link_to 'Log out', destroy_user_session_path, method: :delete

        %ul#nav-mobile.right.hide-on-med-and-down
          = content_for :navbar
        %ul#mobile-demo.side-nav
          = content_for :navbar

    .container
      .col-lg-12.content
        - [:notice, :error, :alert, :warning, :message, :success].each do |type|
          - if flash[type].present?
            .alert.alert-dismissible.alert-success
              %button.close{"data-dismiss" => "alert", :type => "button"} ×
              = flash[type]
        = yield